packages:
- .
resolver: lts-16.27
extra-deps:
- chakra-0.1.0
- git: https://github.com/cackharot/wai-cli.git
  commit: 9f80498a7fa77a660952796119f39da9f83dafef
- prometheus-metrics-ghc-1.0.1.1
- wai-middleware-prometheus-1.0.0
- servant-auth-0.4.0.0
- servant-auth-server-0.4.6.0
- servant-server-0.18.2
- servant-0.18.2
