{
 "title": "Haskell RTS stats",
 "tags": [ "haskell" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(ghc_gcs_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(ghc_cpu_seconds_total{instance=~\"$instance\"}[5m])) by (instance)",
       "legendFormat": "{{Instance}}"
      }
     ]
    },
    {
     "title": "Mutator CPU time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(ghc_mutator_cpu_seconds_total{instance=~\"$instance\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocation rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ghc_allocated_bytes_total{instance=~\"$instance\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Copy data rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ghc_copied_bytes_total{instance=~\"$instance\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GC stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync/Total GC Time",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "ghc_gcdetails_sync_elapsed_seconds/ghc_gcdetails_elapsed_seconds"
      }
     ]
    },
    {
     "title": "Proportion of the GC running time",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "ghc_gc_elapsed_seconds_total/ghc_elapsed_seconds_total"
      }
     ]
    },
    {
     "title": "GC Time proportion",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max(ghc_gc_elapsed_seconds_total{instance=~\"$instance\"} / ghc_elapsed_seconds_total{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total GCs",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "ghc_gcs_total{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Total major GCs",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "ghc_major_gcs_total{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Avg GCs rate",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
     "format": "ops",
     "valueName": "avg",
     "targets": [
      {
       "expr": "irate(ghc_gcs_total{instance=~\"$instance\"}[5m])"
      }
     ]
    },
    {
     "title": "Avg major GCs rate",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
     "format": "ops",
     "valueName": "avg",
     "targets": [
      {
       "expr": "irate(ghc_major_gcs_total{instance=~\"$instance\"}[5m])"
      }
     ]
    },
    {
     "title": "Heap structure",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ghc_gcdetails_live_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}:live"
      },
      {
       "expr": "sum(ghc_gcdetails_compact_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}: compat"
      },
      {
       "expr": "sum(ghc_gcdetails_large_objects_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}:large"
      },
      {
       "expr": "sum(ghc_gcdetails_slop_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}:slop"
      }
     ]
    },
    {
     "title": "GC time details",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(ghc_gcdetails_elapsed_seconds{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}:elapsed"
      },
      {
       "expr": "sum(ghc_gcdetails_sync_elapsed_seconds{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}:sync"
      }
     ]
    }
   ]
  }
 ]
}